language: cpp
script: make
git:
    depth: 2
    quiet: true
matrix:
    include: 
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-6
            env:
                - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        before_install:
            - eval "${MATRIX_EVAL}"
        install:
            - "export CXX=g++-6"
