language: cpp
git:
    depth: 2
    quiet: true
job:
    include: 
        - stage: Build
          script: make
        - stage: Test
          script: ./test.sh

        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-6
            env:
                - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        before_install:
            - eval "${MATRIX_EVAL}"
            - "chmod +x test.sh"
        install:
            - "export CXX=g++-6"
